### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by timemake** [farbodbj/YourMusic#5]
checkPermission function is not working for TIRAMISU due to wrong setting.

- if (VERSION.SDK_INT > TIRAMISU) (X)

- if (VERSION.SDK_INT >= TIRAMISU) (O)

**Comment by farbodbj** [comment]
Thanks for caring and posting the issue, will fix it shortly.

**Comment by farbodbj** [comment]
This bug has been fixed in the following commit: f8bda2aeb2c4424ce2311b7decc6016172ef7cae
